### ISSUE TITLE
Setting RigidBody2D Gravity Scale to 0 prevents state.apply_central_force()

### ISSUE THREAD

**Issue by Cosillow** [appsinacup/godot-rapier-physics#223]
**Describe the bug**
When I set the gravity scale of a RigidBody2d to 0, the body will not move via _integrate_forces().

**To Reproduce**
1. Start up a project with a rigidBody2d and add this script:
```extends RigidBody2D

@export var thrust := Vector2(1000, 1000)

func _integrate_forces(state: PhysicsDirectBodyState2D) -> void:
	var X_DIR = Input.get_axis("ui_left", "ui_right")
	var Y_DIR = Input.get_axis("ui_up", "ui_down")
	thrust * Vector2(X_DIR, Y_DIR).normalized()
	state.apply_central_force(thrust * Vector2(X_DIR, Y_DIR).normalized())
```

2. In the inspector set the Gravity Scale to 0 on the Rigid Body
3. Test with default physics
4. Enable rapier and try again

**Expected behavior**
I expect the body to only be affected by the forces applied in the script and not be affected by gravity. Instead, no forces are applied. (adding back .1 scale works as expected)

**Environment:**
 - OS: Ubuntu 22.04.4 LTS
 - Godot Version v4.3.stable
 - Type 2D slower cross platform deterministic

**Example project(zip)**
[rapier_issue.zip](https://github.com/user-attachments/files/16720925/rapier_issue.zip)

**Comment by Ughuuu** [comment]
Problem appears to be that the body is sleeping, and forces don't wake it up. Fix will be to wake it up when applying a force. If you press the left button eg right as scene starts, it moves the body. If the gravity is 0.1, the body is moving, so its not sleeping. As a workaround you can disable can_sleep on the body until this is fixed. Won't take long to fix I hope tho, but probably will get fixed in 0.8.2
